---
default_install_hook_types: [pre-commit, prepare-commit-msg]
default_stages: [pre-commit]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-yaml
      - id: detect-private-key
        exclude: '(vault.yml.template|filter_catalina.yaml.j2)'
      - id: trailing-whitespace
  - repo: https://github.com/avilaton/add-msg-issue-prefix-hook
    rev: v0.0.11
    hooks:
      - id: add-msg-issue-prefix
        args:
          - --template={}
          - --pattern=[a-zA-Z0-9]{1,10}-[0-9]{1,6}
  - repo: https://github.com/ansible/ansible-lint.git
    rev: v24.7.0
    hooks:
      - id: ansible-lint
        stages: [manual]
        additional_dependencies:
          - .
          - ansible-core==2.16.6
          - jmespath
        language_version: python3.11
  - repo: https://github.com/IamTheFij/ansible-pre-commit.git
    rev: v0.1.2
    hooks:
      - id: encryption-check
        always_run: true
        files: vault.ya?ml$

