---
- name: aws_bitbucket_dc_node.yml
  hosts: aws_node_local
  become: true
  module_defaults:
    ansible.builtin.uri:
      http_agent: "ansible-httpget_{{ ansible_play_name }}"
    ansible.builtin.get_url:
      http_agent: "ansible-httpget_{{ ansible_play_name }}"

  vars:
    # See group_vars/aws_node_local.yml, which pull vars from the environment.
    atl_product_family: "stash"
    atl_product_edition: "bitbucket"
    atl_product_user: "bitbucket"

    atl_use_system_jdk: true
    java_major_version: "17"
    atl_download_format: "tarball"

    atl_product_home: "/var/atlassian/application-data/bitbucket"
    atl_nfs_mountpoint: "{{ atl_shared_mountpoint }}/bitbucket/shared"
    atl_nfs_target: "{{ atl_shared_mountpoint }}/bitbucket/shared"
    atl_nfs_version: "3"


    atl_startup_systemd_params:
      - "UMask=0027"
      - "LimitNOFILE=4096"
      - "Environment=BITBUCKET_HOME={{ atl_product_home }}"
      - "Environment=JAVA_HOME=/usr/lib/jvm/java"
      - "Environment=JVM_MAXIMUM_MEMORY={{ atl_jvm_heap }}"
      - "Environment=JVM_MINIMUM_MEMORY={{ atl_jvm_heap }}"
      - "Environment=JVM_SUPPORT_RECOMMENDED_ARGS={{ atl_jvm_opts }}"
    atl_startup_exec_options:
      - "--no-search"

  roles:
    - role: linux_common
    - role: aws_common
    # For Bitbucket DC clusters that store repos on Bitbucket Mesh(https://confluence.atlassian.com/bitbucketserver/bitbucket-data-center-and-server-8-0-release-notes-1115659343.html#BitbucketDataCenterandServer8.0releasenotes-mesh),
    # nodes may be setup to use EFS instead of NFS for shared_home by not defining 'atl_fileserver_host'
    - { role: aws_shared_fs_config, when: (atl_fileserver_host is not defined or atl_fileserver_host | length == 0) and (atl_efs_id | length > 0) }
    - { role: nfs_mount, when : (atl_fileserver_host is defined) and (atl_fileserver_host|length > 0) }
    - role: product_common
    - role: product_install
    - { role: database_init, tags: [database] }
    - role: bitbucket_config
    - role: product_startup
    - role: bitbucket_dataset_restore
      when: atl_bitbucket_dataset_url is search ("(http|https)://")


