---
- name: aws_bitbucket_nfs_node.yml
  hosts: aws_node_local
  become: true
  module_defaults:
    ansible.builtin.uri:
      http_agent: "ansible-httpget_{{ ansible_play_name }}"
    ansible.builtin.get_url:
      http_agent: "ansible-httpget_{{ ansible_play_name }}"

  vars:
    # See group_vars/aws_node_local.yml, which pull vars from the environment.
    atl_product_family: "stash"
    atl_product_edition: "bitbucket"
    atl_product_user: "bitbucket"

    atl_nfs_mountpoint: "{{ atl_shared_mountpoint }}/bitbucket/shared"
    atl_nfs_target: "{{ atl_shared_mountpoint }}/bitbucket/shared"

  roles:
    - role: linux_common
    - role: aws_common
    - role: nfs_server
    - role: diy_backup
