mesh_install_dir: /opt/atlassian/mesh
bitbucket_mesh_maven_repo: https://packages.atlassian.com/maven-external
bitbucket_mesh_version: "1.3.1"

# if basic_auth is required for download of atlassian installable artifact, provide the name of an AWS Secrets Manager secret
#  with values for both password and username
atl_download_secret_name: ''