---
driver:
  name: docker
platforms:
  - name: amazon_linux2023
    image: amazonlinux:2023
    groups:
      - aws_node_local
    platform: linux/amd64
  - name: ubuntu_lts
    image: ubuntu:jammy
    groups:
      - aws_node_local
    platform: linux/amd64
provisioner:
  name: ansible
  env:
    ANSIBLE_COLLECTIONS_PATH: "../../../../"
  inventory:
    links:
      group_vars: ../../../../group_vars/
verifier:
  name: testinfra
